---
# tasks file for roles/node-exporter

- name: check if node exporter exist
  stat:
    path: "{{ node_exporter_bin }}"
  register: __check_node_exporter_present
  tags: [never, node]

- name: create node exporter user
  user:
    name: "{{ node_exporter_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  tags: [never, node]

- name: create node exporter config directory 
  file:
    path: "{{ node_exporter_dir_conf }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
  tags: [never, node]

- name: download and unzip node exporter if not exist
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no
  when: __check_node_exporter_present.stat.exists == false
  tags: [never, node]

- name: move the binary to the final destination
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: 0755
    remote_src: yes
  when: __check_node_exporter_present.stat.exists == false
  tags: [never, node]

- name: clean 
  file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/ 
    state: absent
  tags: [never, node]

- name: install service
  template: 
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root  
    group: root 
    mode: 0755
  notify: reload_daemon_and_restart_node_exporter
  tags: [never, node]

- meta: flush_handlers
  tags: [never, node]
  

