---
- name: install prometheus 
  hosts: monitor
  become: true
  remote_user: root
  vars:
    ansible_ssh_private_key_file: /home/suman/.ssh/id_rsa
  tags:
    - prometheus
  roles:
    - prometheus