---
- name: Installation & Configuration Of Mysqld-Exporter 
  hosts: mysqld
  become: true
  gather_facts: false
  remote_user: root
  vars_files:
    - vars/mysqld_vars.yml
    - vars/grafana_vars.yml
  roles:
   - mysqld-exporter
   - add-scrape-config
   - import-grafana-dashboard