---
- name: install mysqld_exporter
  hosts: mysqld
  become: true
  remote_user: root
  vars_files:
    - sshkey_vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ privatekeypath }}"
  tags:
    - mysqld-exporter
  roles:
    - mysqld-exporter

- name: Create Mysqld Dashboard
  hosts: grafana
  become: true
  remote_user: root
  vars_files:
    - vars/grafana_vars.yml
    - sshkey_vars.yml 
  vars:
    ansible_ssh_private_key_file: "{{ privatekeypath }}"
  tasks:
    - name: Import Mysql Exporter Dashboard
      community.grafana.grafana_dashboard:
        grafana_url: "{{ grafanaurl }}"  # Grafana URL
        grafana_user: "{{ grafanauser }}"                       # Grafana username
        grafana_password: "{{ grafanapassword }}"               # Grafana password
        state: present                              # To create a new dashboard
        folder: my_project                          # Folder ID where the dashboard should be created
        overwrite: yes                              # Set to 'yes' to overwrite if dashboard exists
        dashboard_url: "https://grafana.com/api/dashboards/14057/revisions/1/download"  # Url to dashboard JSON file
    