---
- name: Installation & Configuration Of Node-Exporter 
  hosts: node
  become: true
  gather_facts: false
  remote_user: root
  vars_files:
    - vars/node_vars.yml
    - vars/grafana_vars.yml
  roles:
   - node-exporter
   - add-scrape-config
   - import-grafana-dashboard