---
- name: Installation & Configuration of Rabbitmq-Exporter
  hosts: rabbitmq
  become: true
  gather_facts: false
  remote_user: root
  vars_files:
    - vars/rabbitmq_vars.yml
    - vars/grafana_vars.yml
  roles:
   - rabbitmq-exporter
   - add-scrape-config
   - import-grafana-dashboard