---
- name: install redis-exporter
  hosts: redis
  become: true
  remote_user: root
  vars_files:
    - vars/sshkey_vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ privatekeypath }}"
  tags:
    - redis-exporter
  roles:
    - redis-exporter

- name: Create Redis Exporter Dashboard
  hosts: grafana
  become: true
  remote_user: root
  vars_files:
    - vars/grafana_vars.yml
    - vars/sshkey_vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ privatekeypath }}"
  tasks:
    - name: Import Redis Exporter Dashboard
      grafana_dashboard:
        grafana_url: "{{ grafanaurl }}"  # Grafana URL
        grafana_user: "{{ grafanauser }}"                       # Grafana username
        grafana_password: "{{ grafanapassword }}"               # Grafana password
        state: present                              # To create a new dashboard
        folder: my_project                          # Folder ID where the dashboard should be created
        overwrite: yes                              # Set to 'yes' to overwrite if dashboard exists
        dashboard_url: "https://grafana.com/api/dashboards/17507/revisions/1/download"  # Url to dashboard JSON file