---
- name: installation & Configuration Of Redis-Exporter 
  hosts: redis
  become: true
  gather_facts: false
  remote_user: root
  vars_files:
    - vars/redis_vars.yml
    - vars/grafana_vars.yml
  roles:
   - redis-exporter
   - add-scrape-config
   - import-grafana-dashboard