---
# handlers file for roles/mysqld-exporter
- name: reload_daemon_and_restart_prometheus
  delegate_to: prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
    enabled: yes