---
# tasks file for roles/redis-exporter

- name: check if redis exporter exist
  stat:
    path: "{{ redis_exporter_bin }}"
  register: __check_redis_exporter_present

- name: create redis exporter user
  user:
    name: "{{ redis_exporter_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create redis exporter config directory 
  file:
    path: "{{ redis_exporter_dir_conf }}"
    state: directory
    owner: "{{ redis_exporter_user }}"
    group: "{{ redis_exporter_user }}"

- name: download and unzip redis exporter if not exist
  unarchive:
    src: "https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes
    validate_certs: no
  when: __check_redis_exporter_present.stat.exists == false

